### ISSUE TITLE
Settings class "emptying"file if syntax error

### ISSUE THREAD

**Issue by REHERC** [Ciastex/Spectrum#23]
Example with a json file called "myFile.json" 
```json
{
    "setting1": "value1"
    "setting2": true
}
```
Note the above json is missing a comma (,) after "value1"
---
Then if i use
```csharp
var settings = new Settings("myFile");
```
if will actually empty the file and write this to it instead
```json
{ }
```

I have never used settings.Save();

**Comment by JohnCorby** [comment]
it's because of this savelater variable
![image](https://user-images.githubusercontent.com/26337121/50552196-a65d0680-0c42-11e9-97f0-38b17233424f.png)
settings.Save() _is_ actually used in constructor.
saveLater is set to True if an error is thrown while trying to parse the json. Since the Save() function saves based off of the Setting object's entries (Settings is basically a special Dictionary), and said object currently has no entries, myFile.json is overwritten with an empty dict aka "{}".
I'm not sure why the saveLater variable is even needed in the first place, as all it appears to do it cause this bug.
Here's the fixed code.
![image](https://user-images.githubusercontent.com/26337121/50552261-11f3a380-0c44-11e9-84d1-0e3a8079bb82.png)
