### ISSUE TITLE
CheatMode Issues

### ISSUE THREAD

**Issue by Seeker14491** [Ciastex/Spectrum#26]
Looking at the code for the new `CheatMode` class, I believe I've found some issues:

- calling `CheatMode.Enable()` while playing a track will not disable leaderboard upload for that track, as we're only updating `anyGameplayCheatsUsedThisLevel_` when the scene loads.
- the class methods have no effect at all when playing online, due to the `AnyGameplayCheatEnabled_` property getter being written like this

```csharp
private bool AnyGameplayCheatEnabled_
    {
        get
        {
            return this.gameplayCheatsRecognized_ && this.anyGameplayCheatsUsedThisLevel_;
        }
    }
```

and `this.gameplayCheatsRecognized_` being set to false by the game when playing online inside `CheatsManager.OnEventSceneLoadFinished()`.

**Comment by Ciastex** [comment]
I've changed a lot of Spectrum functionality in the [experimental_cheat_system](/Ciastex/Spectrum/tree/experimental_cheat_system) branch. Feel free to suggest any modifications, but be aware this branch can change without a warning, since I'm not entirely satisfied with how this system is utilized inside Spectrum Manager project.

**Comment by Seeker14491** [comment]
This shouldn't be closed yet; I looked at the new CheatRegistry code, and it looks like the second point is still an issue.
